apiVersion: v1
data:
  accessKey: bkZ1ak1JSTFSWjRFdzBvdXFreWwK 
  secretKey: UWpsMmxZc29mY2owMThTME5BQkV6SU5FNzF5V1F4VE9pWEVBemdXdQo=
kind: Secret
metadata:
  name: argo-s3-credentials
  namespace: argo
type: Opaque
