apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: buildkit-pipeline
spec:
  entrypoint: pipeline

  volumeClaimTemplates:
  - metadata:
      name: workspace
    spec:
     accessModes: ["ReadWriteOnce"]
     storageClassName: hostpath
     resources:
       requests:
         storage: 1Gi
  volumes: 
  - name: docker-config
    secret:
      secretName: docker-config

  templates:

  - name: pipeline
    steps:
    - - name: clone
        template: clone-repo
    - - name: list
        template: list-repo

    - - name: build
        template: build-image

    - - name: update-manifest
        template: update-rollout

    - - name: commit
        template: commit-changes

  ################################################
  # Clone repository
  ################################################

  - name: clone-repo
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          git clone https://github.com/PullaPantangi/roboshop-k8s-26.git /workspace
          echo "after clone"
          ls -R /workspace
      volumeMounts:
      - name: workspace
        mountPath: /workspace
          #  - name: list-repo
          #    container:
          #      image: alpine/git
          #      command: [sh, -c]
          #      args:
          #        - |
          #          "echo $(ls -l /workspace)"
          #      volumeMounts:
          #      - name: workspace
          #        mountPath: /workspace
  - name: list-repo
    container:
      image: alpine
      command: [sh, -c]
      args:
        - |
          echo "Listing workspace directory"
          ls -l /workspace
          echo "Recursive listing"
          ls -R /workspace
      volumeMounts:
      - name: workspace
        mountPath: /workspace
  
  
  ################################################
  # Build image using BuildKit
  ################################################

  - name: build-image
    container:
      image: moby/buildkit:latest
      securityContext:
        privileged: true
      command: [sh, -c]
      args:
        - |
          buildctl-daemonless.sh build \
          --frontend dockerfile.v0 \
          --local context=/workspace/argo_versions_app \
          --local dockerfile=/workspace/argo_versions_app \
          --output type=image,name=pullapantangi/app_version_wf:{{workflow.uid}},push=true
      volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: docker-config
        mountPath: /root/.docker/config.json
        subPath: .dockerconfigjson

  ################################################
  # Update Argo Rollout manifest
  ################################################

  - name: update-rollout
    container:
      image: alpine
      command: [sh, -c]
      args:
        - |
          sed -i 's|image: .*|image: pullapantangi/app_version_wf:{{workflow.uid}}|' /workspace/argo_versions_app/blue-green-rollout.yaml
      volumeMounts:
      - name: workspace
        mountPath: /workspace

  ################################################
  # Commit changes to Git
  ################################################

  - name: commit-changes
    container:
      env:
        - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-creds
                key: token
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          cd /workspace
          git config user.email "rao.linux9@gmail.com"
          git config user.name "pullarao"
          git remote set-url origin https://pullapantangi:${GITHUB_TOKEN}@github.com/PullaPantangi/roboshop-k8s-26.git
          git add .
          git commit -m "update image {{workflow.uid}}"
          git push
      volumeMounts:
      - name: workspace
        mountPath: /workspace
