name: workflow dispatch with inputs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
      version:
        description: "Version to be deployed"
        required: true
        default: 1.1.1
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - name: given env values
        run: |
          echo "Deploying to version: ${{ github.event.inputs.environment }}"
          echo "Deploying application version: ${{ github.event.inputs.version }}"
